apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-trino-users
  namespace: md-pipeline
spec:
  provider:
    static:
      userCredentialsSecret:
        name: trino-users