
apiVersion: v1
kind: Service
metadata:
  name: mdp-hms-postgres
  namespace: md-pipeline
spec:
  type: ClusterIP
  selector:
    app: mdp-hms-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
